"""Paquete modular de modelos de datos SQLModel para SIGRAS - Proteccion Civil (HackaTec 2026).

Exporta todas las entidades de dominio organizadas por tabla de forma transparente.
"""

from sqlmodel import Field, Relationship, SQLModel

from app.models.albergue import (
    Albergue,
    AlbergueBase,
    AlbergueCreate,
    AlbergueDetallePublic,
    AlberguePublic,
    AlberguesPublic,
    AlbergueUpdate,
    EstadoOperativoAlbergue,
)
from app.models.albergue_usuario import (
    AlberguesUsuarioPublic,
    AlbergueUsuario,
    AlbergueUsuarioBase,
    AlbergueUsuarioCreate,
    AlbergueUsuarioPublic,
    AlbergueUsuarioUpdate,
    PersonalAsignadoDetalle,
    TurnoOperativo,
)
from app.models.alerta_riesgo import (
    AlertasZonaRiesgoPublic,
    AlertaZonaRiesgo,
    AlertaZonaRiesgoBase,
    AlertaZonaRiesgoCreate,
    AlertaZonaRiesgoPublic,
    AlertaZonaRiesgoUpdate,
    NivelAlertaRiesgo,
)
from app.models.comun import get_datetime_utc, obtener_fecha_hora_utc
from app.models.grupo_familiar import (
    GrupoFamiliar,
    GrupoFamiliarBase,
    GrupoFamiliarCreate,
    GrupoFamiliarPublic,
    GrupoFamiliarUpdate,
)
from app.models.infraestructura import (
    InventarioInfraestructura,
    InventarioInfraestructuraBase,
    InventarioInfraestructuraCreate,
    InventarioInfraestructuraPublic,
    InventarioInfraestructuraUpdate,
)
from app.models.item import (
    Item,
    ItemBase,
    ItemCreate,
    ItemPublic,
    ItemsPublic,
    ItemUpdate,
)
from app.models.persona_refugiada import (
    EstadoEstancia,
    PersonaRefugiada,
    PersonaRefugiadaBase,
    PersonaRefugiadaCreate,
    PersonaRefugiadaPublic,
    PersonaRefugiadaUpdate,
    PersonasRefugiadasPublic,
    RegistroSalidaRefugiado,
)
from app.models.recurso_humano import (
    InventarioRecursoHumano,
    InventarioRecursoHumanoBase,
    InventarioRecursoHumanoCreate,
    InventarioRecursoHumanoPublic,
    InventarioRecursoHumanoUpdate,
)
from app.models.reporte_ciudadano import (
    EstadoReporteCiudadano,
    NivelPrioridadEmergencia,
    ReporteCiudadano,
    ReporteCiudadanoBase,
    ReporteCiudadanoCreate,
    ReporteCiudadanoPublic,
    ReporteCiudadanoUpdate,
    ReportesCiudadanosPublic,
    TipoEmergenciaCiudadana,
)
from app.models.seguridad import (
    Message,
    NewPassword,
    Token,
    TokenPayload,
    UpdatePassword,
)
from app.models.suministro import (
    CatalogosSuministroPublic,
    CatalogoSuministro,
    CatalogoSuministroBase,
    CatalogoSuministroCreate,
    CatalogoSuministroPublic,
    CatalogoSuministroUpdate,
    CategoriaSuministro,
    InventarioArticuloSuministro,
    InventarioArticuloSuministroBase,
    InventarioArticuloSuministroCreate,
    InventarioArticuloSuministroPublic,
    InventarioArticuloSuministroUpdate,
    InventarioSuministro,
    InventarioSuministroBase,
    InventarioSuministroCreate,
    InventarioSuministroPublic,
    InventarioSuministroUpdate,
    MovimientoSuministro,
    MovimientoSuministroBase,
    MovimientoSuministroCreate,
    MovimientoSuministroPublic,
    TipoMovimientoSuministro,
)
from app.models.usuario import (
    AreaFuncional,
    RolOperativo,
    User,
    UserBase,
    UserCreate,
    UserPublic,
    UserRegister,
    UsersPublic,
    UserUpdate,
    UserUpdateMe,
)

__all__ = [
    # Base y utilidades
    "SQLModel",
    "Field",
    "Relationship",
    "obtener_fecha_hora_utc",
    "get_datetime_utc",
    # Seguridad
    "Message",
    "Token",
    "TokenPayload",
    "NewPassword",
    "UpdatePassword",
    # Usuario
    "RolOperativo",
    "AreaFuncional",
    "UserBase",
    "UserCreate",
    "UserRegister",
    "UserUpdate",
    "UserUpdateMe",
    "User",
    "UserPublic",
    "UsersPublic",
    # Item
    "ItemBase",
    "ItemCreate",
    "ItemUpdate",
    "Item",
    "ItemPublic",
    "ItemsPublic",
    # Albergue
    "EstadoOperativoAlbergue",
    "AlbergueBase",
    "AlbergueCreate",
    "AlbergueUpdate",
    "Albergue",
    "AlberguePublic",
    "AlberguesPublic",
    "AlbergueDetallePublic",
    # Albergue Usuario
    "TurnoOperativo",
    "AlbergueUsuarioBase",
    "AlbergueUsuarioCreate",
    "AlbergueUsuarioUpdate",
    "AlbergueUsuario",
    "AlbergueUsuarioPublic",
    "AlberguesUsuarioPublic",
    "PersonalAsignadoDetalle",
    # Grupo Familiar
    "GrupoFamiliarBase",
    "GrupoFamiliarCreate",
    "GrupoFamiliarUpdate",
    "GrupoFamiliar",
    "GrupoFamiliarPublic",
    # Persona Refugiada
    "EstadoEstancia",
    "PersonaRefugiadaBase",
    "PersonaRefugiadaCreate",
    "PersonaRefugiadaUpdate",
    "RegistroSalidaRefugiado",
    "PersonaRefugiada",
    "PersonaRefugiadaPublic",
    "PersonasRefugiadasPublic",
    # Infraestructura
    "InventarioInfraestructuraBase",
    "InventarioInfraestructuraCreate",
    "InventarioInfraestructuraUpdate",
    "InventarioInfraestructura",
    "InventarioInfraestructuraPublic",
    # Recursos Humanos
    "InventarioRecursoHumanoBase",
    "InventarioRecursoHumanoCreate",
    "InventarioRecursoHumanoUpdate",
    "InventarioRecursoHumano",
    "InventarioRecursoHumanoPublic",
    # Suministros (Catalogo, Inventario N:M, Movimientos y Resumen)
    "CategoriaSuministro",
    "TipoMovimientoSuministro",
    "CatalogoSuministroBase",
    "CatalogoSuministroCreate",
    "CatalogoSuministroUpdate",
    "CatalogoSuministro",
    "CatalogoSuministroPublic",
    "CatalogosSuministroPublic",
    "InventarioArticuloSuministroBase",
    "InventarioArticuloSuministroCreate",
    "InventarioArticuloSuministroUpdate",
    "InventarioArticuloSuministro",
    "InventarioArticuloSuministroPublic",
    "MovimientoSuministroBase",
    "MovimientoSuministroCreate",
    "MovimientoSuministro",
    "MovimientoSuministroPublic",
    "InventarioSuministroBase",
    "InventarioSuministroCreate",
    "InventarioSuministroUpdate",
    "InventarioSuministro",
    "InventarioSuministroPublic",
    # Modulos SIGRAS Proteccion Civil
    "TipoEmergenciaCiudadana",
    "NivelPrioridadEmergencia",
    "EstadoReporteCiudadano",
    "ReporteCiudadanoBase",
    "ReporteCiudadanoCreate",
    "ReporteCiudadanoUpdate",
    "ReporteCiudadano",
    "ReporteCiudadanoPublic",
    "ReportesCiudadanosPublic",
    "NivelAlertaRiesgo",
    "AlertaZonaRiesgoBase",
    "AlertaZonaRiesgoCreate",
    "AlertaZonaRiesgoUpdate",
    "AlertaZonaRiesgo",
    "AlertaZonaRiesgoPublic",
    "AlertasZonaRiesgoPublic",
]
